 # build variables
os: Visual Studio 2015
configuration: Release
platform: x86
environment:
  LibraryVersion: 0.2.0
  BUTLER_API_KEY:
    secure: IKGbHJDnuaMLoqwSVxvD1f6kmzirMzElOInxIKG+tqDpXDCmqNn1NYyGYGovF1dD  
  Butler: C:\projects\asummonerstale\butler.exe
  Output: C:\projects\asummonerstale\output
  
# versioning
version: $(LibraryVersion).{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(LibraryVersion).0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'

# packages
install:
  - if not exist output mkdir $(Output)
  - cinst 7zip -x86
  - cinst 7zip.commandline -x86
  - ps: |
      $tempDir="$pwd\temp"
      $installerUrl="http://www.monogame.net/releases/v3.4/MonoGameSetup.exe"
      $installerFile="$tempDir\MonoGameSetup.zip"
      $installerExtracted="$tempDir\MonoGameSetup"
      $programFiles = "${env:ProgramFiles(x86)}\"
      
      $butlerDownload = "https://dl.itch.ovh/butler/windows-386/head/butler.exe"
      $butlerInstallLocation = "$tempdir\butler.exe"
      
      Write-Host "Downloading MonoGame to $installerFile..."
      If ((Test-Path  $tempDir) -eq 0) {
          New-Item -ItemType Directory $tempDir
      }
      Invoke-WebRequest $installerUrl -OutFile $installerFile
      
      Write-Host "Extracting MonoGame to $installerExtracted..."
      7z x -y $installerFile -o"$installerExtracted"
      Write-Host "Copying the MonoGame content pipeline to $programFiles..."
      Copy-Item "$installerExtracted\`$PROGRAMFILES\MSBuild\MonoGame" "$programFiles\MSBuild" -Recurse 
      
      Write-Host "Downloading and installing butler"
      
      Invoke-WebRequest $butlerDownload -OutFile $butlerInstallLocation
      
      Copy-Item $butlerInstallLocation C:\projects\asummonerstale\butler.exe
# build
branches:
  only:
    - master
before_build:
  - nuget restore
build: 
  project: C:\projects\asummonerstale\ASummonersTale.sln
  verbosity: normal
after_build:
  - ps: |
      $ErrorActionPreference = "Stop"
      
      $nugetVersion = "$env:APPVEYOR_BUILD_VERSION"
      
      Write-Host "Copying the output files..."
      copy C:\projects\asummonerstale\ASummonersTale\bin\Windows\x86\Release\ASummonersTale.exe $(Output)
      copy C:\projects\asummonerstale\ASummonersTale\bin\Windows\x86\Release\*.dll $(Output)
    
      Copy-Item C:\projects\asummonerstale\ASummonersTale\bin\Windows\x86\Release\Content $(Output) -recurse
      
 - cmd:
   $(Butler) push blindsidegames/a-summoners-tale:windows-alpha
    
# artifacts
artifacts: 
  - path: $(Output)
    name: ASummonersTale-$(APPVEYOR_BUILD_VERSION) 
    type: zip 
    
deploy:
  - provider: GitHub
    auth_token:
      secure: LKf3G1SYKih8vIVOX9WmOdSW9CDwAqxrCBgVzyZP+2EzNaqJTOn6GcpmliAXJnMV
    artifact: $(Output)\ASummonersTale-$(APPVEYOR_BUILD_VERSION)       
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true
      
notifications:
- provider: Email
  to:
  - robertjawoods@gmail.com
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
